# Generated by Django 2.1.7 on 2019-05-20 17:35

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', tinymce.models.HTMLField(max_length=200, verbose_name='question')),
                ('question_fr', tinymce.models.HTMLField(max_length=200, verbose_name='question')),
                ('answer_en', tinymce.models.HTMLField(verbose_name='answer')),
                ('answer_fr', tinymce.models.HTMLField(verbose_name='answer')),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name_en', tinymce.models.HTMLField(max_length=200, verbose_name='topic')),
                ('topic_name_fr', tinymce.models.HTMLField(max_length=200, verbose_name='topic')),
                ('number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='faq.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('number', 'topic')},
        ),
    ]
