# Generated by Django 2.1.7 on 2019-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_fr',
            field=models.CharField(max_length=200, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name_en',
            field=models.CharField(max_length=200, verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name_fr',
            field=models.CharField(max_length=200, verbose_name='topic'),
        ),
    ]
