# Generated by Django 2.2.2 on 2019-06-30 11:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20190520_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number'], 'verbose_name': 'str_Question', 'verbose_name_plural': 'str_Questions'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['number'], 'verbose_name': 'str_Topic', 'verbose_name_plural': 'str_Topics'},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_en',
            field=tinymce.models.HTMLField(verbose_name='str_answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_fr',
            field=tinymce.models.HTMLField(verbose_name='str_answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200, verbose_name='str_question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_fr',
            field=models.CharField(max_length=200, verbose_name='str_question'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name_en',
            field=models.CharField(max_length=200, verbose_name='str_Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name_fr',
            field=models.CharField(max_length=200, verbose_name='str_Topic'),
        ),
    ]
