dist: xenial
language: python

python:
  - "3.7"

services: postgresql

env:
  - DJANGO=2.2.2

before_install:
  - export DJANGO_SETTINGS_MODULE=salon_ulm_blois.settings.travis

install:
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py collectstatic
  - coverage run manage.py test
  # - python manage.py migrate
  # - python manage.py test

after_success:
  coveralls
