# Generated by Django 2.2.3 on 2019-07-11 17:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='str_Page_name', unique=True)),
            ],
            options={
                'verbose_name': 'str_page',
                'verbose_name_plural': 'str_pages',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='str_Chunk_Key_help_text', max_length=255, unique=True, verbose_name='str_Key')),
                ('content_en', tinymce.models.HTMLField(verbose_name='str_Content')),
                ('content_fr', tinymce.models.HTMLField(blank=True, verbose_name='str_Content')),
                ('description_en', models.CharField(help_text='str_Short_description', max_length=64, verbose_name='str_Description')),
                ('description_fr', models.CharField(blank=True, help_text='str_Short_description', max_length=64, verbose_name='str_Description')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='pages.Page')),
            ],
            options={
                'verbose_name': 'str_chunk',
                'verbose_name_plural': 'str_chunks',
            },
        ),
    ]
