# Generated by Django 2.1.4 on 2019-02-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='A unique name for this chunk of content', max_length=255, unique=True, verbose_name='Key')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('content_fr', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('description', models.CharField(blank=True, help_text='Short Description', max_length=64, verbose_name='Description')),
                ('description_fr', models.CharField(blank=True, help_text='Short Description', max_length=64, null=True, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, help_text='Short Description', max_length=64, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'chunk',
                'verbose_name_plural': 'chunks',
            },
        ),
    ]
