# Generated by Django 2.1.7 on 2019-05-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
