# Generated by Django 2.1.4 on 2019-02-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190201_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunk',
            old_name='content',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='chunk',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='chunk',
            name='content_fr',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='description_fr',
            field=models.CharField(blank=True, help_text='Short Description', max_length=64, verbose_name='Description'),
        ),
    ]
