# Generated by Django 2.2.3 on 2019-07-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_chunk_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='display',
            field=models.BooleanField(default=True, help_text='str_chunk_display_help_text', verbose_name='str_Display'),
        ),
    ]
