# Generated by Django 2.1.7 on 2019-05-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190520_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Page name', unique=True)),
            ],
            options={
                'verbose_name': 'slug',
                'verbose_name_plural': 'slugs',
            },
        ),
    ]
