# Generated by Django 2.2.2 on 2019-06-30 11:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190521_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'verbose_name': 'str_chunk', 'verbose_name_plural': 'str_chunks'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'str_page', 'verbose_name_plural': 'str_pages'},
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_en',
            field=tinymce.models.HTMLField(verbose_name='str_Content'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_fr',
            field=tinymce.models.HTMLField(blank=True, verbose_name='str_Content'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='description_en',
            field=models.CharField(help_text='str_Short_description', max_length=64, verbose_name='str_Description'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='description_fr',
            field=models.CharField(blank=True, help_text='str_Short_description', max_length=64, verbose_name='str_Description'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='key',
            field=models.CharField(help_text='str_Chunk_Key_help_text', max_length=255, unique=True, verbose_name='str_Key'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='str_Page_name', unique=True),
        ),
    ]
