# Generated by Django 2.1.4 on 2019-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190208_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name_en',
            field=models.CharField(max_length=200, verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name_fr',
            field=models.CharField(max_length=200, verbose_name='topic'),
        ),
    ]
