# Generated by Django 2.1.4 on 2019-02-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190208_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_en',
            field=models.CharField(max_length=512, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_fr',
            field=models.CharField(max_length=512, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_fr',
            field=models.CharField(max_length=200, verbose_name='question'),
        ),
    ]
