# Generated by Django 2.1.4 on 2019-02-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190211_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_en',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_fr',
            field=models.TextField(verbose_name='answer'),
        ),
    ]
