# Generated by Django 2.1.4 on 2019-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190211_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
