# Generated by Django 2.1.4 on 2019-03-04 21:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190211_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='content_en',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_fr',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
    ]
