# Generated by Django 2.1.7 on 2019-03-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the meeting name (e.g Salon Ulm 2018)', max_length=128)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('fuel_aviable', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(choices=[('AELIA', 'AELIA'), ('AEPAL', 'AEPAL'), ('AIG', 'AIG'), ('AIR COURTAGE', 'AIR COURTAGE'), ('AISCAIR', 'AISCAIR'), ('AISCALE', 'AISCALE'), ('ALBION', 'ALBION'), ('ALKORA', 'ALKORA'), ('ALLIANZ', 'ALLIANZ'), ('ALPHA INSURANCE', 'ALPHA INSURANCE'), ('AMTI', 'AMTI'), ('ASSUAERO', 'ASSUAERO'), ('AXA', 'AXA'), ('BENACQUISTA', 'BENACQUISTA'), ('BHPA', 'BHPA'), ('CATLIN INSURANCE', 'CATLIN INSURANCE')], max_length=64)),
                ('insurance_number', models.CharField(max_length=64)),
                ('licence_number', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('reservation_validation', 'Can validate arrival and fuel reservation'),),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=32, unique=True)),
                ('arrival', models.DateTimeField(default=None, null=True)),
                ('fuel_reservation', models.PositiveIntegerField(default=0)),
                ('fuel_served', models.PositiveIntegerField(default=0)),
                ('flight_plan', models.BooleanField(default=False)),
                ('passanger', models.BooleanField(default=False)),
                ('esthetic_cup', models.BooleanField(default=False)),
                ('to_sell', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=64)),
                ('origin_city_code', models.CharField(blank=True, max_length=32)),
                ('origin_field', models.CharField(blank=True, help_text='Airfield OACI code', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('arrivals_slots', models.PositiveIntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ULM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('PA', 'Paramotor'), ('PE', 'Pendular'), ('MU', 'Multiaxes'), ('AU', 'Autogyre'), ('HE', 'Helicopter'), ('AE', 'Aerostat')], default='MU', max_length=2)),
                ('imatriculation_country', django_countries.fields.CountryField(default='FR', max_length=2)),
                ('imatriculation', models.CharField(max_length=6)),
                ('radio_id', models.CharField(max_length=6)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulm', to='meeting.Pilot')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='depart_time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='meeting.TimeSlot'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='meeting.TimeSlot'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ulm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.ULM'),
        ),
    ]
