# Generated by Django 2.2.9 on 2020-02-24 06:49

import aircraft_registration_field.modelfield
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confirmation_reminder_date', models.DateField(blank=True, null=True)),
                ('automatic_cancelation_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('fuel_aviable', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(max_length=64, verbose_name='str_Insurance_company')),
                ('insurance_number', models.CharField(max_length=64, verbose_name='str_Insurance_number')),
                ('licence_number', models.CharField(max_length=64, verbose_name='str_Licence_number')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='str_helptext_phonenumber', max_length=128, region=None, verbose_name='str_Phone_number')),
                ('street_name', models.CharField(max_length=128, verbose_name='str_street_nnumber_and_name')),
                ('mail_complement', models.CharField(blank=True, max_length=64, verbose_name='str_mail_complement')),
                ('city', models.CharField(max_length=64, verbose_name='str_City')),
                ('city_code', models.CharField(max_length=32, verbose_name='str_City_code')),
                ('country', django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='str_Country')),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('reservation_validation', 'str_Reservation_Validation_Permission'),),
            },
        ),
        migrations.CreateModel(
            name='ULM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor', models.CharField(max_length=32, verbose_name='str_Constructor')),
                ('model', models.CharField(max_length=32, verbose_name='str_Model')),
                ('type', models.CharField(choices=[('PE', 'str_Flex_Wing'), ('MU', 'str_Fixed_Wings'), ('AU', 'str_Rotor_Wings'), ('HE', 'str_Helicopters'), ('AE', 'str_Balloons_and_Airships')], max_length=2, verbose_name='str_Type')),
                ('imatriculation_country', django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='str_Imatriculation_country')),
                ('imatriculation', models.CharField(max_length=6, verbose_name='str_Imatriculation')),
                ('radio_id', aircraft_registration_field.modelfield.AircraftRegistrationField(max_length=10, verbose_name='str_Aircraft_registration_number')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulm', to='meeting.Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('arrivals_slots', models.PositiveIntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=32, unique=True, verbose_name='str_Reservation_number')),
                ('arrival', models.DateTimeField(blank=True, default=None, null=True)),
                ('fuel_reservation', models.PositiveIntegerField(default=0, help_text='str_helptext_fuel_reservation', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='str_Fuel_reservation')),
                ('fuel_served', models.PositiveIntegerField(default=0)),
                ('flight_plan', models.BooleanField(default=False, verbose_name='str_Flight_plan')),
                ('passanger', models.BooleanField(default=False, verbose_name='str_Passanger')),
                ('esthetic_cup', models.BooleanField(default=False, verbose_name='str_Esthetic_cup')),
                ('for_sale', models.BooleanField(default=False, verbose_name='str_For_sale')),
                ('confirmed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('fuel_reservation_confirmed', models.BooleanField(default=False)),
                ('fuel_advance', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('origin_city_code', models.CharField(blank=True, max_length=64, verbose_name='str_Origin_city_code')),
                ('origin_field', models.CharField(blank=True, help_text='str_Airfield_ID', max_length=32, verbose_name='str_Origin_field')),
                ('depart_time_slot', models.ForeignKey(help_text='str_helptext_departure_slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='meeting.TimeSlot', verbose_name='str_Departure_slot')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.Pilot')),
                ('time_slot', models.ForeignKey(help_text='str_helptext_arrival_slot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='meeting.TimeSlot', verbose_name='str_Arrival_slot')),
                ('ulm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='meeting.ULM', verbose_name='str_ULM')),
            ],
        ),
    ]
