# Generated by Django 2.1.4 on 2018-12-20 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the meeting name (e.g Salon Ulm 2018)', max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=64)),
                ('insurance_number', models.CharField(max_length=64)),
                ('licence_number', models.CharField(max_length=64)),
                ('licence_file', models.FileField(blank=True, null=True, upload_to='')),
                ('insurance_file', models.FileField(blank=True, null=True, upload_to='')),
                ('last_update', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=32, unique=True)),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('fuel_reservation', models.PositiveIntegerField(default=0)),
                ('flight_plan', models.BooleanField(default=False)),
                ('passanger', models.BooleanField(default=False)),
                ('esthetic_cup', models.BooleanField(default=False)),
                ('to_sell', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('arrivals_slots', models.PositiveIntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ULM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('imatriculation_country', django_countries.fields.CountryField(default='FR', max_length=2)),
                ('imatriculation', models.CharField(max_length=16)),
                ('radio_id', models.CharField(max_length=16)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Pilot')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.TimeSlot'),
        ),
    ]
