# Generated by Django 2.1.4 on 2018-12-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_remove_pilot_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ulm',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='meeting.ULM'),
            preserve_default=False,
        ),
    ]
