# Generated by Django 2.1.4 on 2018-12-28 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_reservation_ulm'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='registration_end',
            field=models.DateField(default=datetime.datetime(2018, 12, 28, 13, 54, 55, 443146, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='registration_start',
            field=models.DateField(default=datetime.datetime(2018, 12, 28, 13, 55, 17, 525729, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
