# Generated by Django 2.1.7 on 2019-04-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20190328_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ulm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='meeting.ULM'),
        ),
    ]
