# Generated by Django 2.1.7 on 2019-04-05 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20190405_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulm',
            name='radio_id',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{1,2}-[0-9a-zA-Z]{4,5}$', 'Invalid format, ex: F-JAZ3D or OO-F32S')]),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='type',
            field=models.CharField(choices=[('PA', 'Powered Paraglider'), ('PE', 'Flex Wings'), ('MU', 'Fixed Wings'), ('AU', 'Rotor Wings'), ('HE', 'Helicopters'), ('AE', 'Balloons and Airships')], default='MU', max_length=2),
        ),
    ]
