# Generated by Django 2.1.4 on 2019-01-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_meeting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fuel_served',
            field=models.BooleanField(default=False),
        ),
    ]
