# Generated by Django 2.1.4 on 2019-01-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_reservation_fuel_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='fuel_aviable',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
