# Generated by Django 2.1.4 on 2019-01-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20190114_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fuel_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
