# Generated by Django 2.1.4 on 2019-01-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_reservation_fuel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='fuel_quantity',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='fuel_served',
        ),
    ]
