# Generated by Django 2.1.7 on 2019-04-16 16:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_meeting_confirmation_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
