# Generated by Django 2.1.4 on 2019-01-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_auto_20190117_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fuel_served',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
