# Generated by Django 2.1.7 on 2019-04-22 13:00

from django.db import migrations
import radio_call_sign_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_pilot_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulm',
            name='radio_id',
            field=radio_call_sign_field.modelfields.RadioCallSignField(max_length=6),
        ),
    ]
