# Generated by Django 2.1.4 on 2019-01-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_reservation_fuel_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulm',
            name='type',
            field=models.CharField(choices=[('PA', 'Paramotor'), ('PE', 'Pendular'), ('MU', 'Multiaxes'), ('AU', 'Autogyre'), ('HE', 'Helicopter'), ('AE', 'Aerostat')], default='MU', max_length=2),
        ),
    ]
