# Generated by Django 2.1.7 on 2019-04-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_auto_20190429_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.Pilot'),
        ),
    ]
