# Generated by Django 2.1.7 on 2019-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_auto_20190430_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrival',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
