# Generated by Django 2.1.4 on 2019-01-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_auto_20190131_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ulm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.ULM'),
        ),
    ]
