# Generated by Django 2.1.4 on 2019-02-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0015_auto_20190131_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='insurance_company',
            field=models.CharField(choices=[('AELIA', 'AELIA'), ('AEPAL', 'AEPAL'), ('AIG', 'AIG'), ('AISCAIR', 'AISCAIR'), ('AISCALE', 'AISCALE'), ('ALBION', 'ALBION')], default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='meeting.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulm', to='meeting.Pilot'),
        ),
    ]
