# Generated by Django 2.1.7 on 2019-05-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0015_auto_20190503_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='modification_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='modification_date',
        ),
    ]
