# Generated by Django 2.1.4 on 2019-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0016_auto_20190213_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='insurance_company',
            field=models.CharField(max_length=64),
        ),
    ]
