# Generated by Django 2.1.7 on 2019-05-03 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0016_auto_20190503_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
