# Generated by Django 2.1.4 on 2019-03-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0017_auto_20190304_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={'permissions': (('reservation_validation', 'Can validate pilot arrival and fuel reservation'),)},
        ),
    ]
