# Generated by Django 2.1.7 on 2019-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0017_auto_20190503_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fuel_advance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fuel_reservation_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
