# Generated by Django 2.1.7 on 2019-05-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0018_auto_20190506_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='meeting',
        ),
    ]
