# Generated by Django 2.1.4 on 2019-03-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0018_auto_20190305_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={'permissions': (('reservation_validation', 'Can validate arrival and fuel reservation'),)},
        ),
    ]
