# Generated by Django 2.1.4 on 2019-03-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0019_auto_20190305_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='depart_time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='meeting.TimeSlot'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='origin_city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reservation',
            name='origin_city_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='origin_field',
            field=models.CharField(blank=True, help_text='Airfield OACI code', max_length=32),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='meeting.TimeSlot'),
        ),
    ]
