# Generated by Django 2.1.7 on 2019-05-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0019_remove_reservation_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
            preserve_default=False,
        ),
    ]
