# Generated by Django 2.1.7 on 2019-05-20 05:39

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0020_reservation_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulm',
            name='imatriculation_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='type',
            field=models.CharField(choices=[('PA', 'Powered Paraglider'), ('PE', 'Flex Wings'), ('MU', 'Fixed Wings'), ('AU', 'Rotor Wings'), ('HE', 'Helicopters'), ('AE', 'Balloons and Airships')], max_length=2),
        ),
    ]
