# Generated by Django 2.1.4 on 2019-03-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0020_auto_20190311_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='insurance_company',
            field=models.CharField(choices=[('AELIA', 'AELIA'), ('AEPAL', 'AEPAL'), ('AIG', 'AIG'), ('AIR COURTAGE', 'AIR COURTAGE'), ('AISCAIR', 'AISCAIR'), ('AISCALE', 'AISCALE'), ('ALBION', 'ALBION'), ('ALKORA', 'ALKORA'), ('ALLIANZ', 'ALLIANZ'), ('ALPHA INSURANCE', 'ALPHA INSURANCE'), ('AMTI', 'AMTI'), ('ASSUAERO', 'ASSUAERO'), ('AXA', 'AXA'), ('BENACQUISTA', 'BENACQUISTA'), ('BHPA', 'BHPA'), ('CATLIN INSURANCE', 'CATLIN INSURANCE')], max_length=64),
        ),
    ]
