# Generated by Django 2.1.7 on 2019-05-21 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0021_auto_20190520_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
