# Generated by Django 2.1.7 on 2019-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0022_auto_20190521_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
