# Generated by Django 2.1.7 on 2019-05-23 18:05

from django.db import migrations
import radio_call_sign_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0023_auto_20190521_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulm',
            name='radio_id',
            field=radio_call_sign_field.modelfields.RadioCallSignField(max_length=10),
        ),
    ]
