# Generated by Django 2.1.7 on 2019-05-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0024_auto_20190523_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='origin_city_code',
        ),
    ]
