# Generated by Django 2.2.2 on 2019-07-01 08:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0026_auto_20190630_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='str_helptext_phonenumber', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='type',
            field=models.CharField(choices=[('PE', 'str_Flex_Wing'), ('MU', 'str_Fixed_Wings'), ('AU', 'str_Rotor_Wings'), ('HE', 'str_Helicopters'), ('AE', 'str_Balloons_and_Airships')], max_length=2),
        ),
    ]
