# Generated by Django 2.2.2 on 2019-07-03 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0028_auto_20190701_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='fuel_reservation',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='origin_field',
            field=models.CharField(blank=True, help_text='str_Airfield_ID', max_length=32),
        ),
    ]
