# Generated by Django 2.2.2 on 2019-07-03 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import radio_call_sign_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0029_auto_20190703_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='city',
            field=models.CharField(max_length=64, verbose_name='str_City'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='city_code',
            field=models.CharField(max_length=32, verbose_name='str_City_code'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='str_Country'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='insurance_company',
            field=models.CharField(max_length=64, verbose_name='str_Insurance_company'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='insurance_number',
            field=models.CharField(max_length=64, verbose_name='str_Insurance_number'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='licence_number',
            field=models.CharField(max_length=64, verbose_name='str_Licence_number'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='mail_complement',
            field=models.CharField(blank=True, max_length=64, verbose_name='str_mail_complement'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='str_helptext_phonenumber', max_length=128, null=True, region=None, verbose_name='str_Phone_number'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='street_name',
            field=models.CharField(max_length=128, verbose_name='str_street_nnumber_and_name'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='depart_time_slot',
            field=models.ForeignKey(help_text='str_helptext_departure_slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='meeting.TimeSlot', verbose_name='str_Departure_slot'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='esthetic_cup',
            field=models.BooleanField(default=False, verbose_name='str_Esthetic_cup'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='flight_plan',
            field=models.BooleanField(default=False, verbose_name='str_Flight_plan'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='for_sale',
            field=models.BooleanField(default=False, verbose_name='str_For_sale'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='fuel_reservation',
            field=models.PositiveIntegerField(default=0, help_text='str_helptext_fuel_reservation', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='str_Fuel_reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='origin_city',
            field=models.CharField(blank=True, max_length=64, verbose_name='str_Origin_city'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='origin_field',
            field=models.CharField(blank=True, help_text='str_Airfield_ID', max_length=32, verbose_name='str_Origin_field'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passanger',
            field=models.BooleanField(default=False, verbose_name='str_Passanger'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='str_Reservation_number'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(help_text='str_helptext_arrival_slot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='meeting.TimeSlot', verbose_name='str_Arrival_slot'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ulm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='meeting.ULM', verbose_name='str_ULM'),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='constructor',
            field=models.CharField(max_length=32, verbose_name='str_Constructor'),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='imatriculation',
            field=models.CharField(max_length=6, verbose_name='str_Imatriculation'),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='imatriculation_country',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='str_Imatriculation_country'),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='model',
            field=models.CharField(max_length=32, verbose_name='str_Model'),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='radio_id',
            field=radio_call_sign_field.modelfields.RadioCallSignField(max_length=10, verbose_name='str_Aircraft_registration_number'),
        ),
        migrations.AlterField(
            model_name='ulm',
            name='type',
            field=models.CharField(choices=[('PE', 'str_Flex_Wing'), ('MU', 'str_Fixed_Wings'), ('AU', 'str_Rotor_Wings'), ('HE', 'str_Helicopters'), ('AE', 'str_Balloons_and_Airships')], max_length=2, verbose_name='str_Type'),
        ),
    ]
